### ISSUE TITLE
Add Python 3.6 to TravisCI

### ISSUE THREAD

**Issue by babca** [babca/python-gsmmodem#40]
Add Python 3.6 to TravisCI.

**Comment by tomchy** [comment]
It looks like you need to add just a single line inside ``.tavis.yml`` file :slightly_smiling_face: 
(see tomchy@bb7828a, sorry for typo inside commit message)

**Comment by babca** [comment]
That was a quick note from my smartphone 😛  I made another commit without that typo. Thanks!
