### ISSUE TITLE
Exception in _setSmsMemory

### ISSUE THREAD

**Issue by 9dogs** [babca/python-gsmmodem#43]
In `_setSmsMemory` (modem.py:715) `self.write()` with no argument cause TypeError exception:
```TypeError: write() missing 1 required positional argument: 'data'```

I think it's safe to remove empty `self.write()`, correct me if I'm wrong.

**Comment by tomchy** [comment]
Hey!
This is quite old piece of code. I have no idea why is it there, but _maybe_ someone wanted to check if modem is still alive/flush output, so I'd suggest to change it into:
```python
self.write('AT')
```
Nevertheless it seems to cause the same TypeError inside ''current'' master branch of @faucamp repository.
