### ISSUE TITLE
Add the new fork to PIP

### ISSUE THREAD

**Issue by babca** [babca/python-gsmmodem#5]
I've added the fork to pip.
https://pypi.python.org/pypi/python-gsmmodem-new

Please test.

**Comment by petrleocompel** [comment]
Cannot install via pip3.  
```
Collecting python-gsmmodem-new
Could not find a version that satisfies the requirement python-gsmmodem-new (from versions: )
No matching distribution found for python-gsmmodem-new
```

**Comment by babca** [comment]
Thanks for letting me know. I will make a new release and make it available via pip3 later today.

**Comment by babca** [comment]
You can try again: `pip3 install python-gsmmodem-new`

**Comment by petrleocompel** [comment]
Working fine :blush:

**Comment by petrleocompel** [comment]
You can close issue.

**Comment by babca** [comment]
:-)
