### ISSUE TITLE
Old version while installing from pip

### ISSUE THREAD

**Issue by tarelda** [babca/python-gsmmodem#52]
Dunno why, just installs 0.11 instead of 0.12...

**Comment by babca** [comment]
Hi @tarelda,
thanks for pointing that out, that is interesting. I've registered v0.10, v0.11, v0.12 in pip repository: https://pypi.python.org/pypi/python-gsmmodem-new
but only v0.11 is available from command line... 

`pip3 install python-gsmmodem-new==999999`
 Could not find a version that satisfies the requirement python-gsmmodem-new==999999 (from versions: 0.11)
No matching distribution found for python-gsmmodem-new==999999

I don't know the reason ATM.

**Comment by tarelda** [comment]
@babca, I am not familiar with uploading to pypi, but look at this:
`root@0209c693656a:/# pip3 install --verbose --no-cache-dir -I python-gsmmodem-new
Converted retries value: Retry(total=5, connect=None, read=None, redirect=None) -> Retry(total=Retry(total=5, connect=None, read=None, redirect=None), connect=None, read=None, redirect=None)
Converted retries value: Retry(total=5, connect=None, read=None, redirect=None) -> Retry(total=Retry(total=5, connect=None, read=None, redirect=None), connect=None, read=None, redirect=None)
Collecting python-gsmmodem-new
  1 location(s) to search for versions of python-gsmmodem-new:
  * https://pypi.python.org/simple/python-gsmmodem-new/
  Getting page https://pypi.python.org/simple/python-gsmmodem-new/
  Starting new HTTPS connection (1): pypi.python.org
  "GET /simple/python-gsmmodem-new/ HTTP/1.1" 200 242
  Analyzing links from page https://pypi.python.org/simple/python-gsmmodem-new/
    Found link https://pypi.python.org/packages/56/77/f9ffcd4930c1e0ad33bac4208cd76abfeb1ae4af0acd35fd5751dbe4380a/python-gsmmodem-new-0.11.tar.gz#md5=c9d0f278ad3c3ccf343ee6d3b18dd3fb (from https://pypi.python.org/simple/python-gsmmodem-new/), version: 0.11
  Using version 0.11 (newest of versions: 0.11)
  "GET /packages/56/77/f9ffcd4930c1e0ad33bac4208cd76abfeb1ae4af0acd35fd5751dbe4380a/python-gsmmodem-new-0.11.tar.gz HTTP/1.1" 200 96092
  Downloading python-gsmmodem-new-0.11.tar.gz (96kB)
  Downloading from URL https://pypi.python.org/packages/56/77/f9ffcd4930c1e0ad33bac4208cd76abfeb1ae4af0acd35fd5751dbe4380a/python-gsmmodem-new-0.11.tar.gz#md5=c9d0f278ad3c3ccf343ee6d3b18dd3fb (from https://pypi.python.org/simple/python-gsmmodem-new/)
    100% |████████████████████████████████| 102kB 713kB/s
  Running setup.py (path:/tmp/pip-build-em6q9d34/python-gsmmodem-new/setup.py) egg_info for package python-gsmmodem-new
    Running command python setup.py egg_info
    running egg_info
    creating pip-egg-info/python_gsmmodem_new.egg-info
    writing pip-egg-info/python_gsmmodem_new.egg-info/PKG-INFO
    writing requirements to pip-egg-info/python_gsmmodem_new.egg-info/requires.txt
    writing dependency_links to pip-egg-info/python_gsmmodem_new.egg-info/dependency_links.txt
    writing top-level names to pip-egg-info/python_gsmmodem_new.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/python_gsmmodem_new.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'pip-egg-info/python_gsmmodem_new.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'pip-egg-info/python_gsmmodem_new.egg-info/SOURCES.txt'
  Source in /tmp/pip-build-em6q9d34/python-gsmmodem-new has version 0.11, which satisfies requirement python-gsmmodem-new from https://pypi.python.org/packages/56/77/f9ffcd4930c1e0ad33bac4208cd76abfeb1ae4af0acd35fd5751dbe4380a/python-gsmmodem-new-0.11.tar.gz#md5=c9d0f278ad3c3ccf343ee6d3b18dd3fb
Collecting pyserial>=3.1.1 (from python-gsmmodem-new)
  1 location(s) to search for versions of pyserial:
  * https://pypi.python.org/simple/pyserial/
  Getting page https://pypi.python.org/simple/pyserial/
  "GET /simple/pyserial/ HTTP/1.1" 200 2102
  Analyzing links from page https://pypi.python.org/simple/pyserial/
    Skipping link https://pypi.python.org/packages/0c/16/2c0b371fc3387945304ee2e0db24cd80d7ef8df1c4fe85617d8cccd8fc06/pyserial-2.3-py2.5.egg#md5=e2944f767a14a91058e67f73526b7f2b (from https://pypi.python.org/simple/pyserial/); unsupported archive format: .egg
    Found link https://pypi.python.org/packages/0d/e4/2a744dd9e3be04a0c0907414e2a01a7c88bb3915cbe3c8cc06e209f59c30/pyserial-3.4-py2.py3-none-any.whl#md5=0e555d61700e0b95a15d8162092c5299 (from https://pypi.python.org/simple/pyserial/), version: 3.4
    Skipping link https://pypi.python.org/packages/1c/ba/5c96d18a04787a7cd90ef353ad8f0a20012bd2fd2f43eb62196e15c46b54/pyserial-2.7.win32_py3k.exe#md5=c6fb580ae7763671297794b8a1d91c9e (from https://pypi.python.org/simple/pyserial/); unsupported archive format: .exe
    Found link https://pypi.python.org/packages/1f/3b/ee6f354bcb1e28a7cd735be98f39ecf80554948284b41e9f7965951befa6/pyserial-3.2.1.tar.gz#md5=7142a421c8b35d2dac6c47c254db023d (from https://pypi.python.org/simple/pyserial/), version: 3.2.1
    Found link https://pypi.python.org/packages/22/64/b76b13dae3ec81ee2e6424c6d30b01e335a7e5d33c5c0014cac0d3e117e4/pyserial-3.2.tar.gz#md5=51aed83f45d94e070de2ff706cffa2b4 (from https://pypi.python.org/simple/pyserial/), version: 3.2
    Skipping link https://pypi.python.org/packages/24/0c/1caef2e25d2c44780ead837a0d68c942c77ec92ddccaafe5333293868e08/pyserial-3.0.win32.exe#md5=a23d97fee6f816a17f546c02265cca43 (from https://pypi.python.org/simple/pyserial/); unsupported archive format: .exe
    Found link https://pypi.python.org/packages/2c/c2/2a391a69730c05a646f27e71e965cf8a0e9ccd72c0f0b870b74d47f3c32b/pyserial-3.2-py2.py3-none-any.whl#md5=bc25ea197f9ec3e99360aed38e149fd4 (from https://pypi.python.org/simple/pyserial/), version: 3.2
    Found link https://pypi.python.org/packages/3c/d8/a9fa247ca60b02b3bebbd61766b4f321393b57b13c53b18f6f62cf172c08/pyserial-3.1.1.tar.gz#md5=2f72100de3e410b36d575e12e82e9d27 (from https://pypi.python.org/simple/pyserial/), version: 3.1.1
    Found link https://pypi.python.org/packages/42/68/41bab8a5e3e50705f25358f043181242fa197f313aa0476908d9852c8dc4/pyserial-3.0.1.tar.gz#md5=c8521e49f8852196aac39431e0901703 (from https://pypi.python.org/simple/pyserial/), version: 3.0.1
    Skipping link https://pypi.python.org/packages/47/c9/7802e11ab388ad1539de716649add8bb8ca8bdff660364b3a404f79c27b7/pyserial-2.7.win32.exe#md5=21555387937eeb79126cde25abee4b35 (from https://pypi.python.org/simple/pyserial/); unsupported archive format: .exe
    Found link https://pypi.python.org/packages/49/db/5704dfc92d9a35f43d10744b0e661eeb1cbddc3bf8bd704592d653d23d86/pyserial-3.1.1-py2.py3-none-any.whl#md5=4b710443b1fd7d4685d301aa07f20539 (from https://pypi.python.org/simple/pyserial/), version: 3.1.1
    Found link https://pypi.python.org/packages/50/a0/4159b8050dc4804f8e863b21bb0ad1bd02c4d35ad9954ee0a8c2e2c2c9a2/pyserial-3.3-py2.py3-none-any.whl#md5=d37e07020d54bf44318117b959bed13a (from https://pypi.python.org/simple/pyserial/), version: 3.3
    Skipping link https://pypi.python.org/packages/67/28/8d7b635c7a5c1b8c33833e57053bdd65d3b1bff18b51a406eda417702e47/pyserial-2.4-py2.5.egg#md5=80f98ec0ef48a22e1527071c8520b6cc (from https://pypi.python.org/simple/pyserial/); unsupported archive format: .egg
    Found link https://pypi.python.org/packages/69/89/24fc8c26e23710a0d8fdf9e8134b28ceeab421d3f3e0165ceca6bdb98193/pyserial-3.0.tar.gz#md5=f94bc6e141d60f17edc7bf8757c4d922 (from https://pypi.python.org/simple/pyserial/), version: 3.0
    Skipping link https://pypi.python.org/packages/6b/a6/0206c0517b508a640408db26310b4666083ad8bfd612f5a4d2bc796005b9/pyserial-3.0.1.win32.exe#md5=a3dbae2ca647e90dbb262d62093302ea (from https://pypi.python.org/simple/pyserial/); unsupported archive format: .exe
    Found link https://pypi.python.org/packages/71/47/623e79ac0e72d7b2164477ade7e96cfade476bf762d06a0732a87daf8c65/pyserial-2.3.tar.gz#md5=707b884fc180b568e207e3bb69b6ce7d (from https://pypi.python.org/simple/pyserial/), version: 2.3
    Skipping link https://pypi.python.org/packages/8a/c6/fb38c1c932faa30f31f80631fc84c77641bf66419151844bb1ce19f1194c/pyserial-py3k-2.5.win32.exe#md5=c7d770dede6f6c6197d9652a7658f18e (from https://pypi.python.org/simple/pyserial/); unsupported archive format: .exe
    Found link https://pypi.python.org/packages/8d/88/cf848688ae011085a6da5a470740dafa3a4b105f84a5f79c3b720c19279c/pyserial-3.3.tar.gz#md5=6afe4c2e47bcec6eb7051b8c1ce19d52 (from https://pypi.python.org/simple/pyserial/), version: 3.3
    Found link https://pypi.python.org/packages/aa/e7/e3109a5db1d76f459987ee3def5a34cd4ea825ac2320bd0704a8189cbc15/pyserial-3.1-py2.py3-none-any.whl#md5=dd199d56fbb257b3277690bcb8591f36 (from https://pypi.python.org/simple/pyserial/), version: 3.1
    Found link https://pypi.python.org/packages/c0/a7/25d801d71d2eecbbf0f1142a9d38aa77be71172295259dabb7d91310289c/pyserial-3.2.1-py2.py3-none-any.whl#md5=cb7dbb38abf35498a183a463a040d871 (from https://pypi.python.org/simple/pyserial/), version: 3.2.1
    Found link https://pypi.python.org/packages/c3/9c/9f97e7749c2373031e5dab6e47adab3eabbd5720615d98845ff8bad5b273/pyserial-2.5.tar.gz#md5=34340820710239bea2ceca7f43ef8cab (from https://pypi.python.org/simple/pyserial/), version: 2.5
    Found link https://pypi.python.org/packages/cc/74/11b04703ec416717b247d789103277269d567db575d2fd88f25d9767fe3d/pyserial-3.4.tar.gz#md5=ed6183b15519a0ae96675e9c3330c69b (from https://pypi.python.org/simple/pyserial/), version: 3.4
    Found link https://pypi.python.org/packages/ce/9c/694ce79a9d4a164e109aeba1a40fba23336f3b7554978553e22a5d41d54d/pyserial-3.1.tar.gz#md5=e849af7f8b7ec75cbc7a53da67c51a51 (from https://pypi.python.org/simple/pyserial/), version: 3.1
    Found link https://pypi.python.org/packages/df/c9/d9da7fafaf2a2b323d20eee050503ab08237c16b0119c7bbf1597d53f793/pyserial-2.7.tar.gz#md5=794506184df83ef2290de0d18803dd11 (from https://pypi.python.org/simple/pyserial/), version: 2.7
    Skipping link https://pypi.python.org/packages/eb/e4/ab1f8c20676c283eae10542027bfd86f4976fec0b53c10c0d76490fe74ba/pyserial-2.5.win32.exe#md5=ea4579b9ad39a4f0171c3ec3da0a8212 (from https://pypi.python.org/simple/pyserial/); unsupported archive format: .exe
    Found link https://pypi.python.org/packages/f3/83/7f287e7550795bd924622e8c07673c2e238ad610f273aa27a07a540330d0/pyserial-2.4.tar.gz#md5=eec19df59fd75ba5a136992897f8e468 (from https://pypi.python.org/simple/pyserial/), version: 2.4
    Found link https://pypi.python.org/packages/fb/93/e350757db177234e77037dbbbf8551c0a6e43b634f375590399fef920fde/pyserial-2.6.tar.gz#md5=cde799970b7c1ce1f7d6e9ceebe64c98 (from https://pypi.python.org/simple/pyserial/), version: 2.6
  Using version 3.4 (newest of versions: 3.1.1, 3.2, 3.2.1, 3.3, 3.4)
  "GET /packages/0d/e4/2a744dd9e3be04a0c0907414e2a01a7c88bb3915cbe3c8cc06e209f59c30/pyserial-3.4-py2.py3-none-any.whl HTTP/1.1" 200 193717
  Downloading pyserial-3.4-py2.py3-none-any.whl (193kB)
  Downloading from URL https://pypi.python.org/packages/0d/e4/2a744dd9e3be04a0c0907414e2a01a7c88bb3915cbe3c8cc06e209f59c30/pyserial-3.4-py2.py3-none-any.whl#md5=0e555d61700e0b95a15d8162092c5299 (from https://pypi.python.org/simple/pyserial/)
    100% |████████████████████████████████| 194kB 1.5MB/s
Installing collected packages: pyserial, python-gsmmodem-new

  Running setup.py install for python-gsmmodem-new ...     Running command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-em6q9d34/python-gsmmodem-new/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-zr350psc-record/install-record.txt --single-version-externally-managed --compile
    running install
    running build
    running build_py
    creating build
    creating build/lib
    creating build/lib/gsmmodem
    copying gsmmodem/compat.py -> build/lib/gsmmodem
    copying gsmmodem/gprs.py -> build/lib/gsmmodem
    copying gsmmodem/__init__.py -> build/lib/gsmmodem
    copying gsmmodem/serial_comms.py -> build/lib/gsmmodem
    copying gsmmodem/pdu.py -> build/lib/gsmmodem
    copying gsmmodem/modem.py -> build/lib/gsmmodem
    copying gsmmodem/util.py -> build/lib/gsmmodem
    copying gsmmodem/exceptions.py -> build/lib/gsmmodem
    creating build/lib/gsmtermlib
    copying tools/gsmtermlib/terminal.py -> build/lib/gsmtermlib
    copying tools/gsmtermlib/atcommands.py -> build/lib/gsmtermlib
    copying tools/gsmtermlib/posoptparse.py -> build/lib/gsmtermlib
    copying tools/gsmtermlib/trie.py -> build/lib/gsmtermlib
    copying tools/gsmtermlib/__init__.py -> build/lib/gsmtermlib
    running build_scripts
    creating build/scripts-3.5
    copying and adjusting tools/gsmterm.py -> build/scripts-3.5
    copying and adjusting tools/sendsms.py -> build/scripts-3.5
    copying and adjusting tools/identify-modem.py -> build/scripts-3.5
    changing mode of build/scripts-3.5/gsmterm.py from 644 to 755
    changing mode of build/scripts-3.5/sendsms.py from 644 to 755
    changing mode of build/scripts-3.5/identify-modem.py from 644 to 755
    running install_lib
    running install_egg_info
    running egg_info
    writing dependency_links to python_gsmmodem_new.egg-info/dependency_links.txt
    writing python_gsmmodem_new.egg-info/PKG-INFO
    writing top-level names to python_gsmmodem_new.egg-info/top_level.txt
    writing requirements to python_gsmmodem_new.egg-info/requires.txt
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'python_gsmmodem_new.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'python_gsmmodem_new.egg-info/SOURCES.txt'
    Copying python_gsmmodem_new.egg-info to /usr/local/lib/python3.5/dist-packages/python_gsmmodem_new-0.11.egg-info
    running install_scripts
    copying build/scripts-3.5/identify-modem.py -> /usr/local/bin
    copying build/scripts-3.5/gsmterm.py -> /usr/local/bin
    copying build/scripts-3.5/sendsms.py -> /usr/local/bin
    changing mode of /usr/local/bin/identify-modem.py to 755
    changing mode of /usr/local/bin/gsmterm.py to 755
    changing mode of /usr/local/bin/sendsms.py to 755
    writing list of installed files to '/tmp/pip-zr350psc-record/install-record.txt'
done
  Removing source in /tmp/pip-build-em6q9d34/python-gsmmodem-new
Successfully installed pyserial-3.4 python-gsmmodem-new-0.11
Cleaning up...
Converted retries value: Retry(total=0, connect=None, read=None, redirect=None) -> Retry(total=Retry(total=0, connect=None, read=None, redirect=None), connect=None, read=None, redirect=None)
Converted retries value: Retry(total=0, connect=None, read=None, redirect=None) -> Retry(total=Retry(total=0, connect=None, read=None, redirect=None), connect=None, read=None, redirect=None)
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.`
It seems that pip is trying to download it from https://pypi.python.org/simple/python-gsmmodem-new/ and indeed 0.12 is missing here

**Comment by lcnittl** [comment]
Should be fixed with newest release
