### ISSUE TITLE
Long SMS Concatenation

### ISSUE THREAD

**Issue by ajhalls** [babca/python-gsmmodem#55]
Working with the sample code here: http://blog.wathmal.me/create-your-own-sms-gateway/ which uses this package, the message concatenation doesn't seem to be working.

Specifically when I use

   ` pdu = sms.to_pdu()[0]`
I get part one of the message, but if I use
   ` pdu = sms.to_pdu()[1]`
I get part 2, but if I use:
`    pdu = sms.to_pdu()`

It doesn't concatenate. Any tips / working examples?

**Comment by babca** [comment]
Are you sure it uses this package? :-) I don't think so.

Btw. you can try something like this 
```
pdu = sms.to_pdu()
concatenated = ''.join(pdu)
```
