### ISSUE TITLE
Fix unit tests after rapid merging

### ISSUE THREAD

**Issue by babca** [babca/python-gsmmodem#6]
Some unit tests are now broken.

I suggest to revert a locally cloned repo to the last v0.9 commit 29ca5f5ab030f3907f2d38d60f354a73c8382431, add one commit after the other and reveal which commits break the tests and why.

Anyone able to help?

**Comment by tomchy** [comment]
I have just found out that commit 47facc8 breaks "test_decode (test.test_pdu.TestSmsPdu)" unit tests.
Reverting it solves all errors inside test_pdu set.
@babca Could you recheck your commit and update tests if your update was correct?

**Comment by tomchy** [comment]
Half of errors inside modem tests are due to the changes made by me inside 4c0187e
It introduces ```AT+CSCS``` command which switches between message encoding schemes, but unit tests and fake modems are not aware of it.
I will try to update them and fix modem SMS tests soon :slightly_smiling_face:

**Comment by babca** [comment]
great progress!
https://github.com/babca/python-gsmmodem/commit/47facc8c05b3d4d63c9ff202e5cff033574d2c08 was meant to resolve https://github.com/babca/python-gsmmodem/issues/15
Is test_pdu fixable easily? I will look into it tomorrow. :-)

**Comment by tomchy** [comment]
Well - if you roll back your commit it solves all PDU unittests :slightly_smiling_face:

**Comment by babca** [comment]
done

**Comment by tomchy** [comment]
Could you fix ``coverage`` indicator inside  README.rst ? :slightly_smiling_face:

**Comment by babca** [comment]
New indicators added, now in SVG. :slightly_smiling_face:

**Comment by tomchy** [comment]
Coveralls still points to the faucamp repository :slightly_smiling_face:
Is this service for free and you can add link to your repo/branch or it is only for premium users? :slightly_smiling_face:

**Comment by babca** [comment]
It has the same business model as Github and Travis CI, it's free for open source projects, so I created a new Coveralls account and redirected the badge to it.

**Comment by babca** [comment]
thank you tomchy
