### ISSUE TITLE
Does not work on Python 3.x

### ISSUE THREAD

**Issue by petrkr** [babca/python-gsmmodem#91]
``` 
 File "/usr/local/bin/sendsms.py", line 95, in send_sms
    text = raw_input('> ')
NameError: name 'raw_input' is not defined
```

**Comment by tomchy** [comment]
Hi @petrkr !
I've seen PRs that made it possible to run this library on python3.x. I guess, tools were not a part of this PR.
The fix seems to be simple, are you willing to fix it and submit a PR?

**Comment by petrkr** [comment]
Seems somewhen this was fixed, so I closing this issue.
